### ISSUE TITLE
Duplicate navbar entries for user profile

### ISSUE THREAD

**Issue by oldaccountarchived** [bcejmxjs/blackbelt#2]
Currently there are 2 different places this is displayed. Once in the dropdown under the users name (preferred location) and also next to the other navbar items.

**Comment by sissisnothere** [comment]
In my opinion, it think the user's profile should show in the navbar.  Because in the user's profile page, use can get every information they need (check for process, send email, watch video..). It should be place in the spotlight next the navbar.

**Comment by oldaccountarchived** [comment]
I definitely see your train of thought there. I think I have a pretty dope compromise.
