### ISSUE TITLE
Course add accessible to non admin/instructor.

### ISSUE THREAD

**Issue by corya14** [bcejmxjs/blackbelt#8]
See images below.
![image](https://cloud.githubusercontent.com/assets/7156047/6887871/77928d76-d63a-11e4-97dd-ac1d922ed093.png)
![image](https://cloud.githubusercontent.com/assets/7156047/6887874/895c2666-d63a-11e4-81fa-96bdb298abfc.png)

**Comment by oldaccountarchived** [comment]
Luckily it doesn't let them add it, since the backend security is in place ;)

**Comment by corya14** [comment]
Fixed in 9bb6cef46da6fcc312a998b804b00f0429b9018d.
